### ISSUE TITLE
Can't Add iKommunicate as Signalk Web Socket Connection

### ISSUE THREAD

**Issue by mmchruser** [digitalyacht/ikommunicate#6]
I can't successfully add iKommunicate gateway as a WebSocket "Connection" on a SignalK Server.  It only results in 501 error.  I can connect web socket using chrome web socket tool no issue.

But adding iKommunicate gateway as a WebSocket "Connection" on the SignalK Server results in 501 error.

/home/pi/.signalk/settings.json
...
   {
      "pipeElements": [
        {
          "type": "providers/simple",
          "options": {
            "logging": true,
            "type": "SignalK",
            "subOptions": {
              "type": "ws",
              "host": "192.168.1.98",
              "port": "80",
              "providerId": "53353100-4148-484e-3230-383039353035",
              "useDiscovery": false
            },
            "providerId": "53353100-4148-484e-3230-383039353035"
          }
        }
      ],
      "id": "53353100-4148-484e-3230-383039353035",
      "enabled": true
    }

![image](https://user-images.githubusercontent.com/31142190/77671287-99fa5300-6f44-11ea-9db6-de110a8d0be9.png)

Unexpected server response: 501

**Comment by mmchruser** [comment]
Works fine with UDP but of course iKommunicate only outputs NMEA 0183 on UDP and I can't get the NMEA 2000 data.

**Comment by sumps** [comment]
I think it is linked to a change in the way they open a websocket now on the Signal K server. I think they use the subscribe=none option for some reason, whereas we only support subscribe=self or subscribe=all on iKommunicate.

We need to bring in one of the Signal K developers - are you on the Signal K Slack channel?

**Comment by mmchruser** [comment]
Ah ok, thank you so much for the response!  I will try to find the slack channel now!

**Comment by mmchruser** [comment]
I did also post he issue on SignalK github.

https://github.com/SignalK/signalk-server-node/issues/1005

**Comment by mmchruser** [comment]
Are you saying I can add something in the subscription field to me it work?  I am not sure of the format.  I have tried the following

none
self
all
subscribe=none
subscribe=self
subscribe=all

**Comment by sumps** [comment]
I am in communication with the SK team now - should have more to tell you soon.

There was a recent change that appears to have broken this websocket connection.

**Comment by mmchruser** [comment]
Wonderful! RE: The support, not about the broken ws connection.

**Comment by mmchruser** [comment]
FYI: https://github.com/SignalK/signalk-server-node/issues/1005

**Comment by mmchruser** [comment]
PER sbender9 commented 1 hour ago

This is not working because the iKommunicate does not conform to the SignalK subscription specs. It does not support subscription=none.

This was broke in the node server when I upgraded to use the new signalk-is-client library.

I will work to fix this, it probably won’t be unit next week.

I’m the meantime you can use node server version 1.20.0.

**Comment by mmchruser** [comment]
I can confirm 1.20.0 it is working. Instrument panel now is not but I wasn't planning on using it anyway! Thank you!

**Comment by mmchruser** [comment]
Has iKommunicate given up on the vision?

**Comment by mmchruser** [comment]
Sad...Anyway I found a work around.  I used node-red to connect to the iK signalK gateway and then sent it to the SignalK server with a "signalk-send-pathvalue node".  

Let me know if anyone needs help with it.  I hired a great guy that knew nothing about SignalK but knows Node-Red and he got it done!  Thanks to https://github.com/alexmed

**Comment by mmchruser** [comment]
I can't believe I am the only one connecting an iK to SignalK!
